<?php

$businesses = [
    [
        'name' => 'Auckland Plumbing Experts',
        'industry' => 'Construction & Trades',
        'category' => 'Plumbing',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Mt Eden', 'Newmarket', 'Ponsonby', 'North Shore'],
        'description' => 'Licensed plumbers for leak repairs, hot water cylinders, blocked drains, bathroom plumbing, and urgent call-outs.',
        'services' => ['Leak repairs', 'Blocked drains', 'Hot water cylinders', 'Bathroom plumbing', 'Emergency plumbing'],
        'tags' => ['plumber', 'plumbing', 'drainage', 'pipe repair', 'hot water'],
        'phone' => '021 456 789',
        'email' => 'plumbing@example.com',
        'rating' => 4.8,
        'jobs_completed' => 214,
        'response_time' => 'Usually replies within 2 hours',
    ],
    [
        'name' => 'North Shore Drainage & Plumbing',
        'industry' => 'Construction & Trades',
        'category' => 'Plumbing',
        'location' => 'Auckland',
        'service_areas' => ['Albany', 'Takapuna', 'Glenfield', 'Browns Bay', 'Auckland'],
        'description' => 'Drain unblocking, sewer repairs, water mains, bathroom fit-offs, and small plumbing maintenance jobs.',
        'services' => ['Drain unblocking', 'Sewer repairs', 'Water mains', 'Bathroom fit-off'],
        'tags' => ['drain', 'blocked toilet', 'sewer', 'water leak'],
        'phone' => '020 333 1144',
        'email' => 'northshore.plumbing@example.com',
        'rating' => 4.6,
        'jobs_completed' => 137,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Kiwi Electrical Solutions',
        'industry' => 'Construction & Trades',
        'category' => 'Electrical',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Manukau', 'Henderson', 'Papakura', 'North Shore'],
        'description' => 'Registered electricians for residential and commercial electrical repairs, wiring, switchboards, lighting, and safety checks.',
        'services' => ['Electrical repairs', 'Lighting installation', 'Switchboard upgrades', 'Safety inspections', 'New wiring'],
        'tags' => ['electrician', 'electrical', 'lights', 'wiring', 'switchboard'],
        'phone' => '022 333 444',
        'email' => 'electrical@example.com',
        'rating' => 4.9,
        'jobs_completed' => 301,
        'response_time' => 'Usually replies within 1 hour',
    ],
    [
        'name' => 'Wellington Power Pros',
        'industry' => 'Construction & Trades',
        'category' => 'Electrical',
        'location' => 'Wellington',
        'service_areas' => ['Wellington Central', 'Lower Hutt', 'Porirua', 'Petone'],
        'description' => 'Electrical troubleshooting, new installations, EV charger wiring, office fit-outs, and compliance checks.',
        'services' => ['EV charger installation', 'Office fit-outs', 'Fault finding', 'Compliance checks'],
        'tags' => ['electrician', 'ev charger', 'commercial electrical', 'fault finding'],
        'phone' => '021 448 930',
        'email' => 'wellington.power@example.com',
        'rating' => 4.7,
        'jobs_completed' => 166,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'North Shore Builders',
        'industry' => 'Construction & Trades',
        'category' => 'Renovations',
        'location' => 'Auckland',
        'service_areas' => ['North Shore', 'Albany', 'Takapuna', 'Devonport', 'Auckland'],
        'description' => 'Home renovations, extensions, decks, pergolas, repairs, and general building work for Auckland homeowners.',
        'services' => ['Home renovations', 'Deck building', 'Extensions', 'General repairs', 'Pergolas'],
        'tags' => ['builder', 'building', 'renovation', 'deck', 'extension'],
        'phone' => '020 111 222',
        'email' => 'builders@example.com',
        'rating' => 4.8,
        'jobs_completed' => 89,
        'response_time' => 'Usually replies within 4 hours',
    ],
    [
        'name' => 'Hamilton Renovation Group',
        'industry' => 'Construction & Trades',
        'category' => 'Renovations',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Cambridge', 'Te Awamutu', 'Morrinsville'],
        'description' => 'Kitchen renovations, bathroom upgrades, small extensions, and rental property repair projects.',
        'services' => ['Kitchen renovations', 'Bathroom upgrades', 'Small extensions', 'Rental repairs'],
        'tags' => ['builder', 'renovation', 'kitchen', 'bathroom', 'rental'],
        'phone' => '027 245 6677',
        'email' => 'hamilton.reno@example.com',
        'rating' => 4.5,
        'jobs_completed' => 73,
        'response_time' => 'Usually replies next business day',
    ],
    [
        'name' => 'Harbour Painting & Decorating',
        'industry' => 'Construction & Trades',
        'category' => 'Painting',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Parnell', 'Remuera', 'Mt Roskill', 'North Shore'],
        'description' => 'Interior and exterior painting, plaster touch-ups, colour consultation, rental repainting, and fence staining.',
        'services' => ['Interior painting', 'Exterior painting', 'Plaster repairs', 'Fence staining', 'Rental repainting'],
        'tags' => ['painter', 'painting', 'decorating', 'plaster', 'staining'],
        'phone' => '021 884 210',
        'email' => 'harbour.paint@example.com',
        'rating' => 4.7,
        'jobs_completed' => 142,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Tauranga Tiling Pros',
        'industry' => 'Construction & Trades',
        'category' => 'Tiling',
        'location' => 'Tauranga',
        'service_areas' => ['Tauranga', 'Mount Maunganui', 'Papamoa', 'Bethlehem'],
        'description' => 'Bathroom tiles, kitchen splashbacks, waterproofing coordination, floor tiles, and repair work.',
        'services' => ['Bathroom tiling', 'Kitchen splashbacks', 'Floor tiling', 'Tile repairs'],
        'tags' => ['tiler', 'tiling', 'bathroom', 'splashback', 'waterproofing'],
        'phone' => '022 331 909',
        'email' => 'tauranga.tiling@example.com',
        'rating' => 4.6,
        'jobs_completed' => 58,
        'response_time' => 'Usually replies within 6 hours',
    ],
    [
        'name' => 'Wellington Roofing Co',
        'industry' => 'Construction & Trades',
        'category' => 'Roofing',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Lower Hutt', 'Upper Hutt', 'Kapiti'],
        'description' => 'Roof leak repairs, re-roofing, gutter replacement, roof maintenance, and storm damage checks.',
        'services' => ['Roof leak repairs', 'Re-roofing', 'Gutter replacement', 'Roof maintenance'],
        'tags' => ['roofer', 'roofing', 'roof leak', 'gutter', 'storm damage'],
        'phone' => '027 600 391',
        'email' => 'wellington.roofing@example.com',
        'rating' => 4.7,
        'jobs_completed' => 121,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Sparkle Home Cleaning',
        'industry' => 'Home Services',
        'category' => 'Home Cleaning',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Mt Eden', 'Epsom', 'New Lynn', 'North Shore'],
        'description' => 'Regular home cleaning, end-of-tenancy cleaning, move-out cleaning, and one-off deep cleaning.',
        'services' => ['Weekly cleaning', 'Deep cleaning', 'Move-out cleaning', 'End-of-tenancy cleaning'],
        'tags' => ['cleaner', 'cleaning', 'house cleaning', 'end of tenancy', 'move out'],
        'phone' => '021 234 567',
        'email' => 'cleaning@example.com',
        'rating' => 4.9,
        'jobs_completed' => 254,
        'response_time' => 'Usually replies within 1 hour',
    ],
    [
        'name' => 'Christchurch Clean Team',
        'industry' => 'Home Services',
        'category' => 'Home Cleaning',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Riccarton', 'Hornby', 'Papanui', 'Sumner'],
        'description' => 'Home cleaning, office cleaning, carpet spot cleaning, and spring cleaning packages.',
        'services' => ['Home cleaning', 'Office cleaning', 'Spring cleaning', 'Carpet spot cleaning'],
        'tags' => ['cleaner', 'office cleaning', 'spring clean', 'carpet'],
        'phone' => '020 882 119',
        'email' => 'christchurch.clean@example.com',
        'rating' => 4.5,
        'jobs_completed' => 92,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Dunedin Secure Locksmiths',
        'industry' => 'Home Services',
        'category' => 'Locksmith',
        'location' => 'Dunedin',
        'service_areas' => ['Dunedin', 'Mosgiel', 'Port Chalmers'],
        'description' => 'Emergency lockouts, lock replacement, re-keying, window locks, and rental property lock changes.',
        'services' => ['Emergency lockouts', 'Lock replacement', 'Re-keying', 'Window locks'],
        'tags' => ['locksmith', 'locks', 'keys', 'emergency lockout'],
        'phone' => '027 830 114',
        'email' => 'dunedin.lock@example.com',
        'rating' => 4.6,
        'jobs_completed' => 78,
        'response_time' => 'Usually replies within 2 hours',
    ],
    [
        'name' => 'City Auto Garage',
        'industry' => 'Automotive',
        'category' => 'Mechanics',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Riccarton', 'Linwood', 'Sydenham'],
        'description' => 'Vehicle servicing, diagnostics, brakes, tyres, WOF preparation, and mechanical repairs.',
        'services' => ['Car servicing', 'Diagnostics', 'Brake repairs', 'Tyre services', 'WOF checks'],
        'tags' => ['mechanic', 'car service', 'brakes', 'tyres', 'wof'],
        'phone' => '027 555 888',
        'email' => 'auto@example.com',
        'rating' => 4.4,
        'jobs_completed' => 187,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Auckland Auto Electrical',
        'industry' => 'Automotive',
        'category' => 'Auto Electrical',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Manukau', 'Henderson', 'Onehunga'],
        'description' => 'Battery issues, alternators, starter motors, vehicle wiring, lights, and diagnostic fault scanning.',
        'services' => ['Battery testing', 'Alternator repairs', 'Starter motors', 'Vehicle diagnostics'],
        'tags' => ['auto electrician', 'battery', 'alternator', 'starter motor', 'diagnostic'],
        'phone' => '021 778 443',
        'email' => 'auto.electrical@example.com',
        'rating' => 4.6,
        'jobs_completed' => 119,
        'response_time' => 'Usually replies within 3 hours',
    ],
    [
        'name' => 'Glow Beauty Studio',
        'industry' => 'Beauty & Wellness',
        'category' => 'Beauty Clinics',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Chartwell', 'Frankton', 'Cambridge'],
        'description' => 'Beauty treatments, skincare, waxing, grooming, and personal care services.',
        'services' => ['Skincare', 'Waxing', 'Facials', 'Grooming'],
        'tags' => ['beauty', 'skin', 'facial', 'waxing'],
        'phone' => '021 999 777',
        'email' => 'beauty@example.com',
        'rating' => 4.7,
        'jobs_completed' => 96,
        'response_time' => 'Usually replies next business day',
    ],
    [
        'name' => 'Harbour Catering Co',
        'industry' => 'Food & Hospitality',
        'category' => 'Catering',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Newmarket', 'Parnell', 'North Shore', 'Manukau'],
        'description' => 'Catering and event hospitality for business meetings, private functions, birthdays, and small weddings.',
        'services' => ['Event catering', 'Corporate catering', 'Private functions', 'Finger food'],
        'tags' => ['catering', 'food', 'event', 'hospitality', 'corporate lunch'],
        'phone' => '021 345 678',
        'email' => 'catering@example.com',
        'rating' => 4.5,
        'jobs_completed' => 68,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'NZ Digital Studio',
        'industry' => 'IT & Technology',
        'category' => 'Web Development',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'Wellington', 'Christchurch', 'Remote'],
        'description' => 'Website design, Laravel development, web app support, IT setup, and digital solutions for small businesses.',
        'services' => ['Website design', 'Laravel development', 'Web app support', 'IT setup'],
        'tags' => ['web development', 'website', 'laravel', 'it support', 'software'],
        'phone' => '022 888 666',
        'email' => 'tech@example.com',
        'rating' => 4.8,
        'jobs_completed' => 84,
        'response_time' => 'Usually replies within 2 hours',
    ],
    [
        'name' => 'Harbour Accounting Services',
        'industry' => 'Professional Services',
        'category' => 'Accounting',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'North Shore', 'Manukau', 'Remote'],
        'description' => 'Small business accounting, bookkeeping, GST, payroll, income tax, and Xero support.',
        'services' => ['Bookkeeping', 'GST returns', 'Payroll', 'Income tax', 'Xero support'],
        'tags' => ['accountant', 'accounting', 'gst', 'payroll', 'xero'],
        'phone' => '09 555 1234',
        'email' => 'accounting@example.com',
        'rating' => 4.6,
        'jobs_completed' => 148,
        'response_time' => 'Usually replies next business day',
    ],
];

$additionalBusinessDetails = [
    [
        'name' => 'Canterbury Custom Carpentry',
        'industry' => 'Construction & Trades',
        'category' => 'Carpentry',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Riccarton', 'Rolleston', 'Rangiora'],
        'description' => 'Custom cabinetry, timber repairs, door installation, interior trim, and small residential carpentry projects.',
        'services' => ['Custom cabinetry', 'Timber repairs', 'Door installation', 'Interior trim'],
    ],
    [
        'name' => 'Waikato Flooring Specialists',
        'industry' => 'Construction & Trades',
        'category' => 'Flooring',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Cambridge', 'Te Awamutu', 'Morrinsville'],
        'description' => 'Timber, laminate, vinyl, and hybrid flooring installation for homes, rentals, and small commercial spaces.',
        'services' => ['Timber flooring', 'Laminate flooring', 'Vinyl installation', 'Floor repairs'],
    ],
    [
        'name' => 'Bay Fencing & Gates',
        'industry' => 'Construction & Trades',
        'category' => 'Fencing',
        'location' => 'Tauranga',
        'service_areas' => ['Tauranga', 'Papamoa', 'Mount Maunganui', 'Te Puke'],
        'description' => 'Residential fencing, privacy screens, boundary gates, pool fencing, and damaged fence repairs.',
        'services' => ['Timber fencing', 'Boundary gates', 'Pool fencing', 'Fence repairs'],
    ],
    [
        'name' => 'Queenstown Deck Builders',
        'industry' => 'Construction & Trades',
        'category' => 'Decking',
        'location' => 'Queenstown',
        'service_areas' => ['Queenstown', 'Frankton', 'Arrowtown', 'Wānaka'],
        'description' => 'New timber and composite decks, deck extensions, balustrades, stairs, and seasonal maintenance.',
        'services' => ['Timber decks', 'Composite decking', 'Deck extensions', 'Deck repairs'],
    ],
    [
        'name' => 'Appliance Rescue Waikato',
        'industry' => 'Home Services',
        'category' => 'Appliance Repair',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Cambridge', 'Te Awamutu', 'Huntly'],
        'description' => 'Diagnosis and repair for washing machines, dryers, dishwashers, ovens, and common kitchen appliances.',
        'services' => ['Washing machine repair', 'Dishwasher repair', 'Oven repair', 'Dryer repair'],
    ],
    [
        'name' => 'Wellington Handy Crew',
        'industry' => 'Home Services',
        'category' => 'Handyman Services',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Lower Hutt', 'Porirua', 'Johnsonville'],
        'description' => 'Reliable help with shelves, flat-pack furniture, minor repairs, wall mounting, and property maintenance.',
        'services' => ['Furniture assembly', 'Wall mounting', 'Minor repairs', 'Property maintenance'],
    ],
    [
        'name' => 'Auckland Pest Defence',
        'industry' => 'Home Services',
        'category' => 'Pest Control',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Manukau', 'West Auckland', 'North Shore'],
        'description' => 'Residential pest treatments for ants, cockroaches, rodents, spiders, wasps, and seasonal infestations.',
        'services' => ['Rodent control', 'Ant treatment', 'Cockroach treatment', 'Wasp removal'],
    ],
    [
        'name' => 'Easy Move Christchurch',
        'industry' => 'Home Services',
        'category' => 'Moving Services',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Rolleston', 'Rangiora', 'Lincoln'],
        'description' => 'Home, apartment, office, and single-item moving with careful loading and flexible local scheduling.',
        'services' => ['Home moving', 'Office moving', 'Furniture moving', 'Packing assistance'],
    ],
    [
        'name' => 'Tauranga Pool Care',
        'industry' => 'Home Services',
        'category' => 'Pool Maintenance',
        'location' => 'Tauranga',
        'service_areas' => ['Tauranga', 'Papamoa', 'Mount Maunganui', 'Bethlehem'],
        'description' => 'Routine pool cleaning, water testing, chemical balancing, equipment checks, and green-pool recovery.',
        'services' => ['Pool cleaning', 'Water testing', 'Chemical balancing', 'Equipment checks'],
    ],
    [
        'name' => 'Shoreline Car Wash',
        'industry' => 'Automotive',
        'category' => 'Car Wash',
        'location' => 'Auckland',
        'service_areas' => ['Takapuna', 'Albany', 'Glenfield', 'Browns Bay'],
        'description' => 'Exterior hand washing, interior vacuuming, wheel cleaning, and convenient maintenance wash packages.',
        'services' => ['Exterior hand wash', 'Interior vacuum', 'Wheel cleaning', 'Maintenance wash'],
    ],
    [
        'name' => 'Waikato Tyre Centre',
        'industry' => 'Automotive',
        'category' => 'Tyre Services',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Chartwell', 'Frankton', 'Cambridge'],
        'description' => 'New tyres, puncture repairs, wheel balancing, tyre rotations, and pressure safety checks.',
        'services' => ['New tyres', 'Puncture repair', 'Wheel balancing', 'Tyre rotation'],
    ],
    [
        'name' => 'Christchurch Panel Works',
        'industry' => 'Automotive',
        'category' => 'Panel Beating',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Hornby', 'Sydenham', 'Wigram'],
        'description' => 'Collision repairs, dent removal, bumper repairs, panel refinishing, and insurance assessment support.',
        'services' => ['Collision repairs', 'Dent removal', 'Bumper repairs', 'Panel refinishing'],
    ],
    [
        'name' => 'Capital Vehicle Inspections',
        'industry' => 'Automotive',
        'category' => 'Vehicle Inspection',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Lower Hutt', 'Porirua', 'Petone'],
        'description' => 'Independent pre-purchase inspections, safety checks, diagnostic scans, and written vehicle condition reports.',
        'services' => ['Pre-purchase inspections', 'Safety checks', 'Diagnostic scans', 'Condition reports'],
    ],
    [
        'name' => 'Precision Car Detailing',
        'industry' => 'Automotive',
        'category' => 'Car Detailing',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Newmarket', 'Epsom', 'Onehunga'],
        'description' => 'Interior detailing, paint enhancement, stain removal, protective coatings, and vehicle presentation packages.',
        'services' => ['Interior detailing', 'Paint enhancement', 'Stain removal', 'Protective coating'],
    ],
    [
        'name' => 'South Island Tow Assist',
        'industry' => 'Automotive',
        'category' => 'Towing Services',
        'location' => 'Dunedin',
        'service_areas' => ['Dunedin', 'Mosgiel', 'Port Chalmers', 'Waitati'],
        'description' => 'Local vehicle towing, breakdown recovery, accident transport, and scheduled vehicle relocation.',
        'services' => ['Breakdown towing', 'Accident recovery', 'Vehicle relocation', 'Local towing'],
    ],
    [
        'name' => 'Central City Family Practice',
        'industry' => 'Healthcare & Medical',
        'category' => 'General Practice',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Grafton', 'Newmarket', 'Parnell'],
        'description' => 'General health consultations, routine check-ups, repeat prescriptions, vaccinations, and preventative care.',
        'services' => ['General consultations', 'Health check-ups', 'Vaccinations', 'Repeat prescriptions'],
    ],
    [
        'name' => 'Harbour Dental Care',
        'industry' => 'Healthcare & Medical',
        'category' => 'Dental Clinics',
        'location' => 'Wellington',
        'service_areas' => ['Wellington Central', 'Thorndon', 'Newtown', 'Karori'],
        'description' => 'Family dental check-ups, hygiene appointments, fillings, emergency assessments, and preventative care.',
        'services' => ['Dental check-ups', 'Dental hygiene', 'Fillings', 'Emergency assessments'],
    ],
    [
        'name' => 'Active Motion Physio',
        'industry' => 'Healthcare & Medical',
        'category' => 'Physiotherapy',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Riccarton', 'Merivale', 'Papanui'],
        'description' => 'Physiotherapy for sports injuries, workplace strains, post-operative rehabilitation, and mobility improvement.',
        'services' => ['Injury rehabilitation', 'Sports physiotherapy', 'Mobility treatment', 'Exercise programmes'],
    ],
    [
        'name' => 'Wellington Wellbeing Collective',
        'industry' => 'Healthcare & Medical',
        'category' => 'Mental Health Services',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Lower Hutt', 'Porirua', 'Remote'],
        'description' => 'Confidential counselling and wellbeing support for stress, anxiety, relationships, and life transitions.',
        'services' => ['Individual counselling', 'Anxiety support', 'Relationship counselling', 'Online sessions'],
    ],
    [
        'name' => 'Canterbury Medical Centre',
        'industry' => 'Healthcare & Medical',
        'category' => 'Medical Centres',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Addington', 'Riccarton', 'Spreydon'],
        'description' => 'Community medical appointments, minor injury assessments, health screening, and coordinated primary care.',
        'services' => ['Primary care', 'Minor injury care', 'Health screening', 'Nurse appointments'],
    ],
    [
        'name' => 'Community Care Pharmacy',
        'industry' => 'Healthcare & Medical',
        'category' => 'Pharmacy',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton Central', 'Frankton', 'Claudelands', 'Chartwell'],
        'description' => 'Prescription dispensing, medicine advice, selected vaccinations, and everyday community health products.',
        'services' => ['Prescription dispensing', 'Medicine advice', 'Vaccinations', 'Health products'],
    ],
    [
        'name' => 'Ponsonby Hair Collective',
        'industry' => 'Beauty & Wellness',
        'category' => 'Hair Salons',
        'location' => 'Auckland',
        'service_areas' => ['Ponsonby', 'Grey Lynn', 'Auckland Central', 'Freemans Bay'],
        'description' => 'Haircuts, colouring, styling, treatments, and special-event hair services for all hair types.',
        'services' => ['Haircuts', 'Hair colouring', 'Blow waves', 'Hair treatments'],
    ],
    [
        'name' => 'Hamilton Nail Lounge',
        'industry' => 'Beauty & Wellness',
        'category' => 'Nail Salons',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton Central', 'Chartwell', 'Rototuna', 'Frankton'],
        'description' => 'Manicures, pedicures, gel polish, nail art, and tidy maintenance appointments in a relaxed studio.',
        'services' => ['Manicures', 'Pedicures', 'Gel polish', 'Nail art'],
    ],
    [
        'name' => 'Restore Massage Therapy',
        'industry' => 'Beauty & Wellness',
        'category' => 'Massage Therapy',
        'location' => 'Tauranga',
        'service_areas' => ['Tauranga', 'Mount Maunganui', 'Papamoa', 'Bethlehem'],
        'description' => 'Relaxation, deep-tissue, sports, and targeted massage sessions tailored to individual comfort and goals.',
        'services' => ['Relaxation massage', 'Deep-tissue massage', 'Sports massage', 'Targeted treatment'],
    ],
    [
        'name' => 'Cuba Street Barbers',
        'industry' => 'Beauty & Wellness',
        'category' => 'Barbers',
        'location' => 'Wellington',
        'service_areas' => ['Te Aro', 'Wellington Central', 'Newtown', 'Mount Cook'],
        'description' => 'Classic and modern haircuts, fades, beard trims, razor line-ups, and straightforward grooming.',
        'services' => ['Haircuts', 'Skin fades', 'Beard trims', 'Razor line-ups'],
    ],
    [
        'name' => 'Rotorua Day Spa',
        'industry' => 'Beauty & Wellness',
        'category' => 'Spa Services',
        'location' => 'Rotorua',
        'service_areas' => ['Rotorua Central', 'Ohinemutu', 'Fenton Park', 'Ngāpuna'],
        'description' => 'Relaxing facials, body treatments, massage packages, and spa experiences for individuals and couples.',
        'services' => ['Spa facials', 'Body treatments', 'Massage packages', 'Couples packages'],
    ],
    [
        'name' => 'The Garden Table Restaurant',
        'industry' => 'Food & Hospitality',
        'category' => 'Restaurants',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch Central', 'Merivale', 'Riccarton', 'Addington'],
        'description' => 'Seasonal New Zealand dining, group bookings, set menus, and relaxed meals using locally sourced produce.',
        'services' => ['Lunch service', 'Dinner service', 'Group bookings', 'Set menus'],
    ],
    [
        'name' => 'Harbour Brew Cafe',
        'industry' => 'Food & Hospitality',
        'category' => 'Cafes',
        'location' => 'Wellington',
        'service_areas' => ['Wellington Waterfront', 'Te Aro', 'Thorndon', 'Wellington Central'],
        'description' => 'Locally roasted coffee, cabinet food, breakfast, lunch, and convenient takeaway options.',
        'services' => ['Espresso coffee', 'Breakfast', 'Lunch', 'Takeaway food'],
    ],
    [
        'name' => 'Kiwi Street Eats',
        'industry' => 'Food & Hospitality',
        'category' => 'Food Trucks',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Manukau', 'North Shore', 'West Auckland'],
        'description' => 'Mobile street-food service for markets, workplaces, festivals, private parties, and community events.',
        'services' => ['Market service', 'Private events', 'Festival catering', 'Workplace lunches'],
    ],
    [
        'name' => 'Southern Event Hospitality',
        'industry' => 'Food & Hospitality',
        'category' => 'Event Hospitality',
        'location' => 'Dunedin',
        'service_areas' => ['Dunedin', 'Mosgiel', 'Otago Peninsula', 'Central Otago'],
        'description' => 'Event staffing, guest service, bar teams, setup support, and front-of-house coordination.',
        'services' => ['Event staffing', 'Bar service', 'Guest service', 'Setup support'],
    ],
    [
        'name' => 'Aotearoa Software Works',
        'industry' => 'IT & Technology',
        'category' => 'Software Development',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Auckland', 'Christchurch', 'Remote'],
        'description' => 'Custom business software, internal tools, system integrations, automation, and application maintenance.',
        'services' => ['Custom software', 'System integrations', 'Workflow automation', 'Application maintenance'],
    ],
    [
        'name' => 'Mobile First Apps NZ',
        'industry' => 'IT & Technology',
        'category' => 'Mobile App Development',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'Wellington', 'Hamilton', 'Remote'],
        'description' => 'Mobile app design, cross-platform development, prototypes, app improvements, and launch support.',
        'services' => ['App design', 'Cross-platform apps', 'App prototypes', 'Launch support'],
    ],
    [
        'name' => 'Reliable IT Support',
        'industry' => 'IT & Technology',
        'category' => 'IT Support',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Cambridge', 'Tauranga', 'Remote'],
        'description' => 'Small-business helpdesk, computer setup, Microsoft 365 support, backups, and network troubleshooting.',
        'services' => ['Helpdesk support', 'Computer setup', 'Microsoft 365', 'Network troubleshooting'],
    ],
    [
        'name' => 'Kiwi Cyber Defence',
        'industry' => 'IT & Technology',
        'category' => 'Cybersecurity',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Auckland', 'Christchurch', 'Remote'],
        'description' => 'Security reviews, staff awareness training, account protection, risk assessments, and incident preparation.',
        'services' => ['Security reviews', 'Awareness training', 'Risk assessments', 'Incident planning'],
    ],
    [
        'name' => 'South Coast Creative Design',
        'industry' => 'IT & Technology',
        'category' => 'Graphic Design',
        'location' => 'Dunedin',
        'service_areas' => ['Dunedin', 'Queenstown', 'Christchurch', 'Remote'],
        'description' => 'Brand identities, marketing graphics, print layouts, digital assets, and social-media design packages.',
        'services' => ['Brand design', 'Marketing graphics', 'Print design', 'Social media assets'],
    ],
    [
        'name' => 'Growth Path Consulting',
        'industry' => 'Professional Services',
        'category' => 'Business Consulting',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'Hamilton', 'Wellington', 'Remote'],
        'description' => 'Practical strategy, operations improvement, planning workshops, and growth support for small businesses.',
        'services' => ['Business strategy', 'Operations reviews', 'Planning workshops', 'Growth support'],
    ],
    [
        'name' => 'Virtual Admin NZ',
        'industry' => 'Professional Services',
        'category' => 'Administration Services',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Auckland', 'Wellington', 'Remote'],
        'description' => 'Remote administration, inbox organisation, document formatting, scheduling, and customer-service support.',
        'services' => ['Virtual administration', 'Inbox management', 'Document formatting', 'Scheduling'],
    ],
    [
        'name' => 'Delivery Focus Project Management',
        'industry' => 'Professional Services',
        'category' => 'Project Management',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Auckland', 'Christchurch', 'Remote'],
        'description' => 'Project planning, delivery coordination, risk tracking, reporting, and short-term project recovery support.',
        'services' => ['Project planning', 'Delivery coordination', 'Risk tracking', 'Project reporting'],
    ],
    [
        'name' => 'ClearWord Translation Services',
        'industry' => 'Professional Services',
        'category' => 'Translation Services',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'Wellington', 'Hamilton', 'Remote'],
        'description' => 'Business, community, website, and document translation with proofreading and plain-language support.',
        'services' => ['Document translation', 'Website translation', 'Proofreading', 'Community translation'],
    ],
    [
        'name' => 'Family First Law',
        'industry' => 'Legal Services',
        'category' => 'Family Law',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Manukau', 'North Shore', 'Remote'],
        'description' => 'Family-law guidance for separation, parenting arrangements, relationship property, and mediation preparation.',
        'services' => ['Separation advice', 'Parenting arrangements', 'Relationship property', 'Mediation support'],
    ],
    [
        'name' => 'Aotearoa Immigration Legal',
        'industry' => 'Legal Services',
        'category' => 'Immigration Law',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'Hamilton', 'Wellington', 'Remote'],
        'description' => 'Immigration legal services for visa applications, employer matters, residency pathways, and complex cases.',
        'services' => ['Visa applications', 'Residency pathways', 'Employer support', 'Immigration appeals'],
    ],
    [
        'name' => 'Harbour Property Law',
        'industry' => 'Legal Services',
        'category' => 'Property Law',
        'location' => 'Tauranga',
        'service_areas' => ['Tauranga', 'Papamoa', 'Mount Maunganui', 'Remote'],
        'description' => 'Property conveyancing, sale and purchase reviews, refinancing, subdivisions, and first-home guidance.',
        'services' => ['Property conveyancing', 'Agreement reviews', 'Refinancing', 'First-home advice'],
    ],
    [
        'name' => 'FairWork Employment Lawyers',
        'industry' => 'Legal Services',
        'category' => 'Employment Law',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Lower Hutt', 'Porirua', 'Remote'],
        'description' => 'Employment agreements, workplace disputes, disciplinary processes, restructuring, and mediation advice.',
        'services' => ['Employment agreements', 'Workplace disputes', 'Disciplinary advice', 'Mediation support'],
    ],
    [
        'name' => 'Enterprise Business Law',
        'industry' => 'Legal Services',
        'category' => 'Business Law',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Canterbury', 'Dunedin', 'Remote'],
        'description' => 'Commercial contracts, company setup, shareholder matters, business purchases, and practical legal reviews.',
        'services' => ['Commercial contracts', 'Company setup', 'Shareholder matters', 'Business purchases'],
    ],
    [
        'name' => 'Green Paws Veterinary Clinic',
        'industry' => 'Pet Services',
        'category' => 'Veterinary Clinics',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Rototuna', 'Chartwell', 'Cambridge'],
        'description' => 'Routine pet health checks, vaccinations, microchipping, minor procedures, and preventative-care advice.',
        'services' => ['Pet health checks', 'Vaccinations', 'Microchipping', 'Preventative care'],
    ],
    [
        'name' => 'Fluffy Finish Pet Grooming',
        'industry' => 'Pet Services',
        'category' => 'Pet Grooming',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Mount Eden', 'Epsom', 'New Lynn'],
        'description' => 'Dog washing, breed-appropriate grooming, coat trimming, nail care, and tidy-up appointments.',
        'services' => ['Dog grooming', 'Coat trimming', 'Nail care', 'Wash and dry'],
    ],
    [
        'name' => 'Happy Tails Pet Lodge',
        'industry' => 'Pet Services',
        'category' => 'Pet Boarding',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Rolleston', 'Rangiora', 'Lincoln'],
        'description' => 'Short and extended boarding for dogs and cats with daily care, exercise, and owner updates.',
        'services' => ['Dog boarding', 'Cat boarding', 'Daily exercise', 'Extended stays'],
    ],
    [
        'name' => 'Good Dog Training NZ',
        'industry' => 'Pet Services',
        'category' => 'Dog Training',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Lower Hutt', 'Porirua', 'Kapiti'],
        'description' => 'Positive dog-training sessions for puppies, basic manners, recall, lead walking, and behaviour support.',
        'services' => ['Puppy training', 'Basic manners', 'Recall training', 'Behaviour support'],
    ],
    [
        'name' => 'Trusted Pet Sitters',
        'industry' => 'Pet Services',
        'category' => 'Pet Sitting',
        'location' => 'Tauranga',
        'service_areas' => ['Tauranga', 'Papamoa', 'Mount Maunganui', 'Bethlehem'],
        'description' => 'In-home pet visits, feeding, medication support, dog walking, and holiday care updates.',
        'services' => ['Home pet visits', 'Dog walking', 'Feeding visits', 'Holiday pet care'],
    ],
];

$responseTimes = [
    'Usually replies within 2 hours',
    'Usually replies within 4 hours',
    'Usually replies same day',
    'Usually replies next business day',
];

foreach ($additionalBusinessDetails as $index => $details) {
    $emailName = trim(strtolower((string) preg_replace('/[^a-z0-9]+/i', '.', $details['name'])), '.');

    $businesses[] = [
        ...$details,
        'tags' => array_values(array_unique([
            strtolower($details['category']),
            ...array_map('strtolower', $details['services']),
        ])),
        'phone' => sprintf('020 700 %04d', 1000 + $index),
        'email' => $emailName.'@example.com',
        'rating' => round(4.4 + (($index % 5) * 0.1), 1),
        'jobs_completed' => 42 + ($index * 3),
        'response_time' => $responseTimes[$index % count($responseTimes)],
    ];
}

return $businesses;
